
languageCode = "en-us"
theme = "kotkt"
defaultContentLanguage = "nl"
canonifyURLss = false

[languages]
[languages.en]
name = "English"
title = "E.S.R.G. Knights of the Kitchen Table"
weight = 2
[[languages.en.menu.main]]
identifier = "who-are-we"
title = "About us"
url = "/#who-are-we"
weight = 1
[[languages.en.menu.main]]
identifier = "rpgs"
title = "Tabletop roleplay"
url = "/#roleplaying-games"
weight = 2
[[languages.en.menu.main]]
identifier = "larp"
title = "LARP"
url = "/#larp"
weight = 3
[[languages.en.menu.main]]
identifier = "join-us"
title = "Membership"
url = "/#borg"
weight = 5
[[languages.en.menu.main]]
identifier = "bordspellen"
title = "Boardgames"
url = "/#boardgames"
weight = 4
[[languages.en.menu.main]]
identifier = "contact"
title = "Contact"
url = "#contact"
weight = 6
[[languages.en.menu.main]]
identifier = "files"
title = "Downloads"
url = "/downloads"
weight = 7


[languages.nl]
name = "Nederlands"
title = "E.S.R.G. Knights of the Kitchen Table"
weight = 1
[[languages.nl.menu.main]]
identifier = "who-are-we"
title = "Wie zijn wij"
url = "/#who-are-we"
weight = 1
[[languages.nl.menu.main]]
identifier = "rpgs"
title = "Rollenspellen"
url = "/#roleplaying-games"
weight = 2
[[languages.nl.menu.main]]
identifier = "larp"
title = "LARP"
url = "/#larp"
weight = 3
[[languages.nl.menu.main]]
identifier = "join-us"
title = "Lid worden"
url = "/#borg"
weight = 5
[[languages.nl.menu.main]]
identifier = "bordspellen"
title = "Bordspellen"
url = "/#boardgames"
weight = 4
[[languages.nl.menu.main]]
identifier = "contact"
title = "Contact"
url = "#contact"
weight = 6
[[languages.nl.menu.main]]
identifier = "files"
title = "Downloads"
url = "/downloads"
weight = 6
